// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTxFx-qbg-mvYHYHJVq5CcB6PGOG6jPdI',
    appId: '1:41920987554:web:097081325a2a0d436eb2fb',
    messagingSenderId: '41920987554',
    projectId: 'aisip-ono',
    authDomain: 'aisip-ono.firebaseapp.com',
    storageBucket: 'aisip-ono.appspot.com',
    measurementId: 'G-1Y8X6B2JQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd0afxOIZLyBi2aoJULlG7ZH1QSYgSHlc',
    appId: '1:41920987554:android:19aacebda744004f6eb2fb',
    messagingSenderId: '41920987554',
    projectId: 'aisip-ono',
    storageBucket: 'aisip-ono.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpLuO4oC-696P7dCyKDFKwMvt0FWkAjCA',
    appId: '1:41920987554:ios:dde502c0f722f5a26eb2fb',
    messagingSenderId: '41920987554',
    projectId: 'aisip-ono',
    storageBucket: 'aisip-ono.appspot.com',
    androidClientId:
        '41920987554-3npfho91l117nk3bnuhu51caff3ip44v.apps.googleusercontent.com',
    iosClientId:
        '41920987554-6lp5n7jr9v81pu2r6ulihp3ggu25kpse.apps.googleusercontent.com',
    iosBundleId: 'com.aisip.OnO',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpLuO4oC-696P7dCyKDFKwMvt0FWkAjCA',
    appId: '1:41920987554:ios:1f422852f929436b6eb2fb',
    messagingSenderId: '41920987554',
    projectId: 'aisip-ono',
    storageBucket: 'aisip-ono.appspot.com',
    androidClientId:
        '41920987554-3npfho91l117nk3bnuhu51caff3ip44v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvpFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTxFx-qbg-mvYHYHJVq5CcB6PGOG6jPdI',
    appId: '1:41920987554:web:e7bc6c1ef94f09f96eb2fb',
    messagingSenderId: '41920987554',
    projectId: 'aisip-ono',
    authDomain: 'aisip-ono.firebaseapp.com',
    storageBucket: 'aisip-ono.appspot.com',
    measurementId: 'G-46D1KN1JWM',
  );
}
